openapi: 3.1.0
info:
  title: 'Listen Notes AI: Podcast Search, Directory, and Insights'
  description: |
    The podcast search and discovery platform. Search all podcasts and episodes by people, places, or topics.
    It's the best one-stop podcast discovery API for podcast search, podcast directory, and podcast insights.

  termsOfService: "https://ai.listennotes.com/legal.txt"
  version: "2.0"
servers:
- url: https://ai.listennotes.com/api/v2
paths:
  /just_listen:
    get:
      summary: Fetch a random podcast episode
      description: Recently published episodes are more likely to be fetched. Good luck!
      operationId: justListen
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EpisodeSimple'
components:
  schemas:
    EpisodeSimple:
      type: object
      properties:
        title:
          type: string
        listennotes_url:
          $ref: '#/components/schemas/EpisodeLNUrlField'

    EpisodeLNUrlField:
      type: string
      description: The url of this episode

  parameters:
    queryParam:
      name: q
      in: query
      description: |
        Search term, e.g., person, place, topic... You can use double quotes to do verbatim match, e.g., "game of thrones". Otherwise, it's fuzzy search.
      required: true
      style: form
      explode: true
      schema:
        type: string
        example: star wars

